name: Build Release App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set Up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Gradle and Wrapper
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Get Current versionCode and versionName
        id: get_version
        run: |
          VERSION_CODE=$(grep 'versionCode' app/build.gradle.kts | awk '{print $3}' | tr -d "'")
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk '{print $3}' | tr -d "'")
          echo "::set-output name=version_code::$VERSION_CODE"
          echo "::set-output name=version_name::$VERSION_NAME"

      - name: Increment versionCode
        id: increment_version
        run: |
          NEW_VERSION_CODE=$((${{ steps.get_version.outputs.version_code }} + 1))
          sed -i "s/versionCode ${{ steps.get_version.outputs.version_code }}/versionCode $NEW_VERSION_CODE/" app/build.gradle.kts
          echo "::set-output name=new_version_code::$NEW_VERSION_CODE"

      - name: Create Release Tag
        id: create_tag
        run: |
          TAG_VERSION="v${{ steps.get_version.outputs.version_name }}"
          echo "::set-output name=tag_version::TAG_VERSION"

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.GH_ACTIONS_SIGNING_STORE_BASE64 }}
          GH_ACTIONS_SIGNING_STORE_FILE_PATH: ${{ secrets.GH_ACTIONS_SIGNING_STORE_FILE_PATH }}
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > $GH_ACTIONS_SIGNING_STORE_FILE_PATH

      - name: Build Release APK
        env:
          GH_ACTIONS_SIGNING_STORE_FILE_PATH: ${{ secrets.GH_ACTIONS_SIGNING_STORE_FILE_PATH }}
          GH_ACTIONS_SIGNING_STORE_PASSWORD: ${{ secrets.GH_ACTIONS_SIGNING_STORE_PASSWORD }}
          GH_ACTIONS_SIGNING_KEY_ALIAS: ${{ secrets.GH_ACTIONS_SIGNING_KEY_ALIAS }}
          GH_ACTIONS_SIGNING_KEY_PASSWORD: ${{ secrets.GH_ACTIONS_SIGNING_KEY_PASSWORD }}
          GH_ACTIONS_DEV_ACCESS_TOKEN: ${{ secrets.GH_ACTIONS_DEV_ACCESS_TOKEN }}
          GH_ACTIONS_PROD_ACCESS_TOKEN: ${{ secrets.GH_ACTIONS_PROD_ACCESS_TOKEN }}
        run: GH_ACTIONS_FLAG=true ./gradlew app:assembleRelease

      - name: Build Release Bundle
        env:
          GH_ACTIONS_SIGNING_STORE_FILE_PATH: ${{ secrets.GH_ACTIONS_SIGNING_STORE_FILE_PATH }}
          GH_ACTIONS_SIGNING_STORE_PASSWORD: ${{ secrets.GH_ACTIONS_SIGNING_STORE_PASSWORD }}
          GH_ACTIONS_SIGNING_KEY_ALIAS: ${{ secrets.GH_ACTIONS_SIGNING_KEY_ALIAS }}
          GH_ACTIONS_SIGNING_KEY_PASSWORD: ${{ secrets.GH_ACTIONS_SIGNING_KEY_PASSWORD }}
          GH_ACTIONS_DEV_ACCESS_TOKEN: ${{ secrets.GH_ACTIONS_DEV_ACCESS_TOKEN }}
          GH_ACTIONS_PROD_ACCESS_TOKEN: ${{ secrets.GH_ACTIONS_PROD_ACCESS_TOKEN }}
        run: GH_ACTIONS_FLAG=true ./gradlew app:bundleRelease

      - name: Create Github Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: Release ${{ steps.create_tag.outputs.tag_version }}
          tag_name: ${{ steps.create_tag.outputs.tag_version }}
          draft: false
          generate_release_notes: true
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab